// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://pmijfdehtpdlpqvafmbr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtaWpmZGVodHBkbHBxdmFmbWJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMwNDA0OTEsImV4cCI6MjA3ODYxNjQ5MX0.dpzuBGUmCr_ORPdLRK1gNdBbS3vxinXQ9_IHE37hVkU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);